Repository InventorsDev/sdg-007-frontend, pull requests merged in 2021-05, with the labels that each got.

#59 fixed team page
  pages/teamPage.vue
Labels: bug, code

#60 fixing height bug
  pages/teamPage.vue
Labels: bug, code

#61 fixing http bug
  pages/teamPage.vue
Labels: bug

#62 making final adjustments
  assets/images/illustration-intro.png
  components/sideBar.vue
  pages/intro.vue
  pages/subscribePage.vue
  pages/teamArea.vue
Labels: code

#64 fixing backend
  assets/Backend/developer.php
  static/Backend/api.php
  static/Backend/developer.php
  static/Backend/id16550298_drug.sql
  static/Backend/images/collins.jpg
  static/Backend/images/david.jpg
  static/Backend/images/developer.php
  static/Backend/images/joel_olawanle.jpg
  static/Backend/images/tope.jpg
  static/Backend/images/topzy.jpg
Labels: code

#65 removing backend files
  static/Backend/api.php
  static/Backend/developer.php
  static/Backend/id16550298_drug.sql
  static/Backend/images/collins.jpg
  static/Backend/images/david.jpg
  static/Backend/images/developer.php
  static/Backend/images/joel_olawanle.jpg
  static/Backend/images/tope.jpg
  static/Backend/images/topzy.jpg
Labels: code, enhancement

#68 Update Read me
  README.md
Labels: code

#69 Dev
  pages/aboutPage.vue
  pages/home.vue
  pages/index.vue
  pages/intro.vue
  pages/resultPage.vue
  pages/subscribePage.vue
  pages/teamArea.vue
  pages/teamPage.vue
Labels: bug

#70 replacing localstoage with route param
  pages/home.vue
  pages/resultPage.vue
Labels: code, enhancement

#71 fixing pwa
  nuxt.config.js
  static/icon.png
Labels: code, enhancement
